[build]
  functions = "functions" # Specifies the functions directory
  publish = "/" # If your frontend files are in a "public" directory, adjust accordingly

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

