version: 1
services:
  - type: web
    name: ai-chatbot-backend
    env: node
    plan: free
    runtime: nodejs-20  
    buildCommand: npm install
    startCommand: npm start 
    autoDeploy: true
    routes:
      - src: /api/(.*)
        dest: /functions/ask.js